### Users GET
GET http://localhost:3000/users

### User GET
GET http://localhost:3000/users/4acb89a7-0abc-4b27-ad78-7e3e0b6f0045

### User POST
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "armarnen",
  "password": "2342"
}

### User PUT
PUT http://localhost:3000/users/123

### User DELETE
DELETE http://localhost:3000/users/123