
### User GET
GET http://localhost:3000/user/5deb516b-ad5c-43ab-a1bb-ebcef51cb9f0

### User POST
POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "areae",
  "password": "2342"
}

### User PUT
PUT http://localhost:3000/user/123

### User DELETE
DELETE http://localhost:3000/user/123



### Auth POST
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "areae",
  "password": "2342"
}

> {% client.global.set("authToken", response.body.accessToken) %}

### Auth-Test GET
GET http://localhost:3000/auth/test
Authorization: Bearer {{authToken}}

### Post POST
POST localhost:3000/post
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "title1",
  "text": "text1",
  "visibility": false
}